### ISSUE TITLE
remove unmaintained tracker code

### ISSUE THREAD

**Issue by stevemart** [IBM/innovate-digital-bank#2]
The metrics tracker project is no longer maintained.

Remove the following:

- [x] Badge at top of README
- [x] Privacy Notice from Readme
- [x] Disabling Deployment Tracking from Readme
- [x] Use of metric tracker in app, i.e. `require('metrics-tracker-client').track();`
- [x] The metrics-tracker library from requirement.txt or package.json
- [x] The `repository.yml` file at the app level

Update the `deploy to ibm cloud` button to use this image: https://bluemix.net/deploy/button.png

See https://github.com/IBM/watson-conversation-slots-intro/pull/71/files as an example

**Comment by amalamine** [comment]
Done
